<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NHCLPT520" failures="1" tests="2" name="org.runner.Runner" time="11.311" errors="0" timestamp="26 May 2022 07:45:48 GMT" skipped="0">
  <testcase classname="org.runner.Runner" name="runScenario" time="0.319">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.stepdefinition.Steps.i_enter_the_home_page_Sucessfully(Steps.java:63)
at âœ½.I enter the home page Sucessfully(file:src/test/resources/Features/LoginPage.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="org.runner.Runner" name="runScenario" time="10.992"/>
</testsuite> <!-- org.runner.Runner -->
